// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvrlxfskvoyczrcdhbxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cmx4ZnNrdm95Y3pyY2RoYnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzQyNDAsImV4cCI6MjA3MzcxMDI0MH0.Pfb5D84AZTuYXtaxO8RR0abEACvLPjv5xQzfrVXxDg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});